name: Build Android

on:
    workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install yarn
        run: npm install -g yarn

      - name: Install app dependencies
        run: yarn setup

      - name: Configure the platform
        run: yarn clean
        
      - name: Check requirements
        run: cordova prepare

      - name: Build Android prod aab
        run: yarn build android paid dev

      - name: Upload dev APK
        uses: actions/upload-artifact@v3
        with:
          name: app-dev
          path: /home/runner/work/Acode/Acode/platforms/android/app/build/outputs/apk/debug/app-debug.apk